/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "../Drivers/stm32f1xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void DelayTimerInit()
{
	TIM3_Clk_En();
	(TIM3)->CR[0] |= (1 << 0);
	(TIM3)->CNT = 0;
	(TIM3)->PSC = 1023;
}

void delay(uint16_t delay_ms)
{
	(TIM3)->CNT = 0;
	(TIM3)->ARR = (int)(delay_ms * 7.8125);
	while((TIM3)->CNT < (TIM3)->ARR);
}

uint8_t USART_ReadData()
{
	if(((USART2)->SR & (1 << 5)))
	{
		uint8_t data = ((USART2)->DR) & 0x0F;
		return data;
	}
	else
		return 12;
}

void I2C_Write(uint8_t data)
{
	while(!((I2C2)->SR[0] & (1 << 7)));
	(I2C2)->DR = data;
	while(!((I2C2)->SR[0] & (1 << 2)));
}

void LCD_SendCMD(uint8_t CMD)
{
	uint8_t upperNible = (CMD >> 4) & 0x0F;
	uint8_t lowerNible = CMD & 0x0F;
	I2C_Write((upperNible << 4) | 0x0C);
	I2C_Write((upperNible << 4) | 0x08);
	I2C_Write((lowerNible << 4) | 0x0C);
	I2C_Write((lowerNible << 4) | 0x08);
}

void LCD_SendData(uint8_t Data)
{
	uint8_t upperNible = (Data >> 4) & 0x0F;
	uint8_t lowerNible = Data & 0x0F;
	I2C_Write((upperNible << 4) | 0x0D);
	I2C_Write((upperNible << 4) | 0x09);
	I2C_Write((lowerNible << 4) | 0x0D);
	I2C_Write((lowerNible << 4) | 0x09);
}

void LCD_SendText(char* text, uint8_t size)
{
	(I2C2)->CR[0] |= (1 << 8);
	while(!((I2C2)->SR[0] & (1 << 0)));
	(I2C2)->DR = (0x27 << 1);
	while(!((I2C2)->SR[0] & (1 << 1)));
	(void)(I2C2)->SR[1];

	for(int i = 0; i < size; i++)
		LCD_SendData(text[i]);

	(I2C2)->CR[0] |= (1 << 9);
}

void LCD_Init()
{
	(I2C2)->CR[0] &= ~(1 << 0);
	(I2C2)->CR[1] = (36 & 0x3F);
	(I2C2)->CCR = 180;
	(I2C2)->TRISE = 37;
	(I2C2)->CR[0] |= (1 << 0);
}

void LCD_ScreenInit()
{
	delay(50);
	(I2C2)->CR[0] |= (1 << 8);
	while(!((I2C2)->SR[0] & (1 << 0)));
	(I2C2)->DR = (0x27 << 1);
	while(!((I2C2)->SR[0] & (1 << 1)));
	(void)(I2C2)->SR[1];

	LCD_SendCMD(0x33);
	delay(5);
	LCD_SendCMD(0x32);
	delay(1);
	LCD_SendCMD(0x28);
	delay(1);
	LCD_SendCMD(0x0C);
	delay(1);
	LCD_SendCMD(0x01);
	delay(2);
	(I2C2)->CR[0] |= (1 << 9);
}

int main(void)
{
	GPIOA_Clk_En();
	GPIOB_Clk_En();
	(GPIOA)->CR[0] = 0;
	(GPIOA)->CR[0] |= (9 << 8);
	(GPIOA)->CR[0] |= (4 << 12);
	(GPIOB)->CR[0] = 0;
	(GPIOB)->CR[1] = 0;
	(GPIOB)->CR[0] |= (1 << 28);
	(GPIOB)->CR[1] |= (1 << 0);
	(GPIOB)->CR[1] |= (1 << 4);
	(GPIOB)->CR[1] |= (0x0D << 8);
	(GPIOB)->CR[1] |= (0x0D << 12);

	DelayTimerInit();

	USART2_Clk_En();
	I2C2_Clk_En();

	(USART2)->CR[0] |= (1 << 13) | (1 << 2);
	(USART2)->BRR = 0x0341;

	LCD_Init();

	uint8_t lcd_state = -1;

	while(1)
	{
		uint8_t receivedData = USART_ReadData();
		if(receivedData != 12)
		{
			switch(receivedData)
			{
			case 0:
				if(lcd_state != receivedData)
				{
					LCD_ScreenInit();
					LCD_SendText("Class : Angry", 13);
					(GPIOB)->ODR &= ~(0x07 << 7);
					(GPIOB)->ODR |= (1 << 7);
					lcd_state = receivedData;
				}
				break;
			case 1:
				if(lcd_state != receivedData)
				{
					LCD_ScreenInit();
					LCD_SendText("Class : Disgust", 15);
					(GPIOB)->ODR &= ~(0x07 << 7);
					(GPIOB)->ODR |= (1 << 7);
					lcd_state = receivedData;
				}
				break;
			case 2:
				if(lcd_state != receivedData)
				{
					LCD_ScreenInit();
					LCD_SendText("Class : Fear", 12);
					(GPIOB)->ODR &= ~(0x07 << 7);
					(GPIOB)->ODR |= (1 << 7);
					lcd_state = receivedData;
				}
				break;
			case 3:
				if(lcd_state != receivedData)
				{
					LCD_ScreenInit();
					LCD_SendText("Class : Happy", 13);
					(GPIOB)->ODR &= ~(0x07 << 7);
					(GPIOB)->ODR |= (1 << 9);
					lcd_state = receivedData;
				}
				break;
			case 4:
				if(lcd_state != receivedData)
				{
					LCD_ScreenInit();
					LCD_SendText("Class : Neutral", 15);
					(GPIOB)->ODR &= ~(0x07 << 7);
					(GPIOB)->ODR |= (1 << 8);
					lcd_state = receivedData;
				}
				break;
			case 5:
				if(lcd_state != receivedData)
				{
					LCD_ScreenInit();
					LCD_SendText("Class : Sad", 11);
					(GPIOB)->ODR &= ~(0x07 << 7);
					(GPIOB)->ODR |= (1 << 8);
					lcd_state = receivedData;
				}
				break;
			case 6:
				if(lcd_state != receivedData)
				{
					LCD_ScreenInit();
					LCD_SendText("Class : Surprise", 16);
					(GPIOB)->ODR &= ~(0x07 << 7);
					(GPIOB)->ODR |= (1 << 8);
					lcd_state = receivedData;
				}
				break;
			default:
				LCD_ScreenInit();
				LCD_SendText("Unknown!", 8);
				(GPIOB)->ODR &= ~(0x07 << 7);
				lcd_state = -1;
				break;
			}
		}
	}
    /* Loop forever */
	for(;;);
}
